### ISSUE TITLE
[Suggestion] Option to download icon with the color information baked in

### ISSUE THREAD

**Issue by dandv** [ericcornelissen/tmp#149]
### Kind of issue

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description

The icons are useful beyond web applications. Without an HTML context, it's not possible to specify the fill color.

It would be great to make the SVGs downloadable with the color baked in.

**Comment by jorgeamadosoria** [comment]
This is going to be an option when the detail page (#43 ) is done.
Right now a colored icon download option won't be provided in the list because it would conflict with the compact layout design (#17).
This suggestion has been made a couple times before, so it is certainly in our minds.
