### ISSUE TITLE
Icons can't be downloaded because they have `.null` extension in href

### ISSUE THREAD

**Issue by mondeja** [ericcornelissen/tmp#156]
This is happenning in production. I can't replicate it in development.

### Kind of issue 

- [ ] Feature
- [x] Bug
- [ ] Design
- [ ] Other, namely:

#### Firefox

![image](https://user-images.githubusercontent.com/23049315/144873679-697f4a50-bca7-4486-9b63-a5551c131d38.png)

#### Brave browser (Chromium based)

![image](https://user-images.githubusercontent.com/23049315/144873899-7a8cef92-735c-432b-9975-562638b24f8e.png)

**Comment by mondeja** [comment]
Hey @jorgeamadosoria, could you check that [these lines](https://github.com/simple-icons/simple-icons-website/commit/b179d66bcfba310d783b5e987070604bc65fe046#diff-68257fa00104bf768f47a378cf42be0b51cbc397093c1d95ed76663b2eb88b96R36-R42) are working properly? I think that the `${type}` not being properly checked here is causing the error.

**Comment by jorgeamadosoria** [comment]
probably addressed in #157

**Comment by mondeja** [comment]
Confirmed, this has been solved in production!
