### ISSUE TITLE
Some icons are not properly alphabetically ordered

### ISSUE THREAD

**Issue by mondeja** [ericcornelissen/tmp#166]
The end of the page shows some icons that are not the latest alphabetically:

![image](https://user-images.githubusercontent.com/23049315/147395480-136af549-5120-4dd9-8304-64ff4966a185.png)

**Comment by jorgeamadosoria** [comment]
easy fix: needs a sort call in webpack.config

**Comment by mondeja** [comment]
Waybackmachining a bit seems that the problem was introduced in [this commit](https://github.com/simple-icons/simple-icons-website/commit/7aa61345271a3b91390f6a9814053208f86818ec), when simple-icons was bumped to v6, because at [2021 11 28 - 11:37](https://web.archive.org/web/20211128111937/https://simpleicons.org/) the problem didn't exists but at [2021 11 29 - 00:25](https://web.archive.org/web/20211129002503/https://simpleicons.org/) yes.

**Comment by jorgeamadosoria** [comment]
> Waybackmachining a bit seems that the problem was introduced in [this commit](https://github.com/simple-icons/simple-icons-website/commit/7aa61345271a3b91390f6a9814053208f86818ec), when simple-icons was bumped to v6, because at [2021 11 28 - 11:37](https://web.archive.org/web/20211128111937/https://simpleicons.org/) the problem didn't exists but at [2021 11 29 - 00:25](https://web.archive.org/web/20211129002503/https://simpleicons.org/) yes.

it may be true.
The alpha ordering of the icons was assumed in the released npm library up to version 6.
Whatever the publishing process is (I'm not familiar) the icons released in version 6 were not sorted into the overall list.
Regardless of whether that's going to be fixed or not, the website now sorts it after import, so from the website standpoint it doesn't matter anymore.
It would be best if the publishing of the NPM package sorted the icons as previously, though. Just for aesthetics when using the library directly, I suppose.
