### ISSUE TITLE
Website usually fails to load all icons.

### ISSUE THREAD

**Issue by DAflamingFOX** [ericcornelissen/tmp#185]
Website usually fails to load

### Kind of issue 

- [ ] Feature
- [ x] Bug
- [ ] Design
- [ ] Other, namely:

### Description
website takes forever/fails to load unless you go to direct query link.

Should probably implement a way of dynamically loading icons as needed rather than (I assume otherwise idk why its crashing) loading every single icon.

**Comment by mondeja** [comment]
Hi @DAflamingFOX, could you share your browser and version of it in which you've experienced this problem? Not all browsers support lazy loading of icons.

**Comment by DAflamingFOX** [comment]
Hi @mondeja! I am currently using Chrome Version 98.0.4758.81.

**Comment by mondeja** [comment]
Shouldn't be problems with that version, the icons should be lazily loaded. I can't reproduce it. Are you sure that icons are not lazily loaded? Could you share a minimal video loading the page with the "Network" DevTools tab opened?

**Comment by DAflamingFOX** [comment]
Of course the solution could've been turn it off and turn it back on again; I am a little stunned because I remember this happening more than once previously but of course today everything is working properly and website loads snappy quick.

Thanks for helping though @mondeja
