### ISSUE TITLE
Website Constantly Crashing

### ISSUE THREAD

**Issue by sancho1952007** [ericcornelissen/tmp#192]
### Kind of issue 

- [ ] Feature
- [x] Bug
- [ ] Design
- [ ] Other, namely:

### Description
The Website Is Constantly Crashing In Chrome.
Don't Know Why...
Also, If It Loads Then, It Just Hangs & Is Non-Functional Again!

**Comment by mondeja** [comment]
Could you specify the version of Chrome that you're using?

**Comment by sancho1952007** [comment]
99.0.4844.51 (Official Build) (64-bit)

**Comment by mondeja** [comment]
I can't reproduce it. Could you share the specifications of your device?

**Comment by sancho1952007** [comment]
This Might Help You Out: https://i.ibb.co/Rch7fg8/Bug.gif

**Comment by mondeja** [comment]
> This Might Help You Out: https://i.ibb.co/Rch7fg8/Bug.gif

Sorry, but that doesn't help at all. Could you share the specifications of your device?

**Comment by jorgeamadosoria** [comment]
> This Might Help You Out: https://i.ibb.co/Rch7fg8/Bug.gif

the error video is fine, but we would need to know which device you are using (because this does not happen for us in Chrome 99 on our devices) and perhaps a report of what you see in the Console log of Chrome can also help.

**Comment by sancho1952007** [comment]
Console: https://i.ibb.co/qRGBtDM/download.png
I Think It's The Extensions I Have Installed...

Extensions: Adblocker & McAfee WebAdvisor

**Comment by sancho1952007** [comment]
Also, I Tested Disabling The Adblocker Then Also, It Crashed...

**Comment by mondeja** [comment]
Could you post the specifications of your device, please?

**Comment by sancho1952007** [comment]
Windows 11 Single Language
Ram Is 8 GB
512 GB SSD

**Comment by mondeja** [comment]
Thanks! 🤔 That's very strange, I've the same ram and no problems at all... I'll try to reproduce it. Could you also try it disabling the McAfee WebAdvisor extension?

**Comment by jorgeamadosoria** [comment]
> Console: https://i.ibb.co/qRGBtDM/download.png I Think It's The Extensions I Have Installed...
> 
> Extensions: Adblocker & McAfee WebAdvisor

I have adBlocker, and I can get the website just fine. Maybe is either McAfee or the combination of both?
This is interesting. I will try it on my side, and if I can repeat the problem we may want to add a warning on the README about it.

**Comment by wang1212** [comment]
see https://github.com/simple-icons/simple-icons-website/issues/200#issuecomment-1107525638

**Comment by mondeja** [comment]
I'm closing this, feel free to reopen if you are experiencing the issue on incognito mode (without active extensions).
