### ISSUE TITLE
GitHub Repository Link Typo in opencollective.com Website

### ISSUE THREAD

**Issue by ghost** [ericcornelissen/tmp#212]
### Kind of issue 

- [x] Typo

### Description

Just forgot to add `s` on the GitHub repository link of [Open Collective](https://opencollective.com/simple-icons) website.

![61dVO5Yu61](https://user-images.githubusercontent.com/109977275/181753671-cfbe24a2-29e0-466c-b23f-f299a6e3d1b3.png)

**Comment by mondeja** [comment]
Thank you, it is fixed :+1:
