### ISSUE TITLE
URL not indexed on Bing, Yahoo and DuckDuckGo

### ISSUE THREAD

**Issue by alanjacobmathew** [ericcornelissen/tmp#214]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [ ] Design
- [x] Other, namely:

### Description

-  Simple icons website(simpleicons.org) are not indexed by  Bing & Yahoo and hence not indexed on DuckDuckGo , although teh github pages are indexed.
- `http://simpleicons.p2hp.com/` Not sure what this page is but even the favicon is of simpleicons.org

 

![image](https://user-images.githubusercontent.com/33965848/191743382-89b75df7-fa71-4c55-816c-562ed3bc75e7.png)
![image](https://user-images.githubusercontent.com/33965848/191743893-29237038-1151-4c20-8f61-1245f1ee59f3.png)

**Comment by mondeja** [comment]
### Solutions

- [x] **Bing**: Add `https://simpleicons.org` to their index [here](https://www.bing.com/webmasters/submiturl?siteUrl=https://simpleicons.org). Also, we must add a meta tag and a sitemap XML file to the web and add a CNAME record to the DNS server. 
- [x] **Yandex**: add `https://simpleicons.org` to their index [here](https://webmaster.yandex.com/sites/add/). The steps are almost the same.
