### ISSUE TITLE
Add sitemap

### ISSUE THREAD

**Issue by mondeja** [ericcornelissen/tmp#215]
We've just one page but seems that some search engines index better sites with sitemap. Most likely related to #214

**Comment by LitoMore** [comment]
Do we need to create a sitemap record for each icon? Like:

```
# sitemap.txt
https://simpleicons.org/?q=apple
https://simpleicons.org/?q=applearcade
https://simpleicons.org/?q=applemusic
https://simpleicons.org/?q=applenews
```

**Comment by mondeja** [comment]
And images of tools? And PDFs? I think that not but technically seems that could be added. Take into account that a sitemap can't contain more than 50k URLs, so nowadays the file will contain almost 5k URLs including PDFs and SVGs. Do you think that is worth to add it for them?

I'm not a SEO expert but investigating a bit most of the people don't recommend to add all media assets to the sitemap, not even all regular pages.
