### ISSUE TITLE
Add more translations to the website

### ISSUE THREAD

**Issue by mondeja** [ericcornelissen/tmp#227]
Just add a language to `locales/languages.json`, run `npm run locale` and a new file `locales/{language}.po` will be created. Translate the file with an editor like [POEdit](https://poedit.net/download/) and submit a pull request.

- [x] `es` (#218)
- [x] `fr` (#218)
- [x] `it` (#226)
- [x] `zh-CN` (#235)
- [x] `zh-HK` (#239)
- [x] `zh-TW` (#239)
- [x] `pt` (#260)
- [x] `jp` (#271)
- [ ] `ru`
- [ ] `de`
- [ ] ...

**Comment by Andre601** [comment]
Would love to contribute but I have a few issues I quickly mention here (I can open an issue if that is wanted).

The POEditor is reporting duplicate Strings it removed as it violates the PO format or something...

Next, was there a `<language>.mo` file created by the POEditor.

Finally is there this huge error I receive with GitHub Desktop, when I try to push my changes on a new branch to the remote repository: https://hastebin.com/feyalavile.js

Is ther actually any particular reason why POEdit is used and not a system with a site such as Crowdin?

**Comment by LitoMore** [comment]
> The POEditor is reporting duplicate Strings it removed as it violates the PO format or something...

We could update the template to what POEditor expected. PRs welcome.

> Next, was there a `<language>.mo` file created by the POEditor.

Please check your editor settings before use.

> Finally is there this huge error I receive with GitHub Desktop, when I try to push my changes on a new branch to the remote repository: [hastebin.com/feyalavile.js](https://hastebin.com/feyalavile.js)

Looks like this error is not related to our project.

> Is there actually any particular reason why POEdit is used and not a system with a site such as Crowdin?

We have very few contents that require translation. The Gettext PO Files is enough to use. The Crowdin might not be necessary.

**Comment by Andre601** [comment]
> Looks like this error is not related to our project.

Weirdly enough does it only happen with this particular project. :/

**Comment by LitoMore** [comment]
@Andre601 See https://github.com/desktop/desktop/issues/12562. Please use Windows Terminal + WSL with Git directly as a workaround on your local.

I'm not going to discuss this error here due to is not related to our project.

**Comment by mondeja** [comment]
Closing as have been added more translations.
