### ISSUE TITLE
There's no java icon

### ISSUE THREAD

**Issue by sinbee0402** [ericcornelissen/tmp#238]
### Kind of issue 

- [x] Feature
- [ ] Bug
- [ ] Design
- [ ] Other, namely:

### Description
Java icon is not here.
It doesn't come out even if I search.
I checked my github profile, but only the Java badge didn't have Icon, so I tried to fix it, but the Simple-Icons website didn't show Java.

**Comment by LitoMore** [comment]
See https://github.com/simple-icons/simple-icons/issues/7374.

**Comment by sinbee0402** [comment]
Oh, thank you.

**Comment by LitoMore** [comment]
@sinbee0402 BTW, you could use OpenJDK icon as a workaround.

https://simpleicons.org/?q=openjdk
