### ISSUE TITLE
Outdated Contributing file

### ISSUE THREAD

**Issue by Andre601** [ericcornelissen/tmp#257]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [ ] Design
- [x] Other, namely: Outdated CONTRIBUTING.md file in this repository

### Description

The issue isn't related to the website's content, but the actual repository itself (This one).
The `CONTRIBUTING.md` file mentions the following thing:

"2. Create a new branch from the latest `develop`"

This information is incorrect, as the repository itself does not have any `develop` branch to create a new branch for. I assume that the file has been adabted from the main simple-icons repository and that this was just an oversight (Or that that repo did such a branch but it has been removed).

I'm open to PR a small fix if that is wanted and if it is ineed a incorrect info.

**Comment by LitoMore** [comment]
Yes. PRs welcome.
