### ISSUE TITLE
Showing number of Search Results

### ISSUE THREAD

**Issue by Gaurav-Verma07** [ericcornelissen/tmp#258]
**Feature**
Hii everyone,
I saw in the website that it's not showing the number of search results.
So, I would like to add a new feature that shows no. of search results

**Comment by LitoMore** [comment]
The search feature is for searching for a specific icon.  I don't think there is any value in showing totals here.

**Comment by LitoMore** [comment]
Closing. Feel free to reopen it if you can provide some good use cases showing totals.
