### ISSUE TITLE
Website design suggestions

### ISSUE THREAD

**Issue by marienneLopez** [ericcornelissen/tmp#275]
### Kind of issue 
- [X] Feature

### Description
Would it be possible to add an on-site help page on how to use the site?
Also, maybe make the site's footer and header floating on top of the search results?

**Comment by mondeja** [comment]
- Controls are always on top of the search results. I'm not sure why you would need the header always shown. Would you mind to clarify that?
- Footer is too big to maintain in the screen always and is not clear what benefit could bring that.
- The site seems very straitghtforward and simple to understand it so I think that a help page is not neccesary. What you don't understand?

**Comment by mondeja** [comment]
Closing due to lack of additional information. Feel free to reopen it if you deem necessary.
