### ISSUE TITLE
"Sort by color" icon is confusing

### ISSUE THREAD

**Issue by kidonng** [ericcornelissen/tmp#276]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [x] Design
- [ ] Other, namely:

### Description

<img width="163" alt="截屏2023-03-06 23 34 51" src="https://user-images.githubusercontent.com/44045911/223159134-93867bea-dddf-4b6f-8351-9e4bb5391d3f.png">

That icon has nothing to do with color. `[title]` attribute is useless for mobile users, so I struggled to understand what it means (thought it was about popularity) until I open the page on a computer.

**Comment by mondeja** [comment]
I agree and would suggest to use a palette icon instead. The problem is the difficulity of his creation making it clear using just two colors. We are trying to maintain the controls in two colors for consistency and to highlight the colors of the brands, but suggestions are always welcome.

**Comment by kidonng** [comment]
It looks fine (using [the palette icon from Material Design Icons](https://icon-sets.iconify.design/mdi/palette/)):

<img width="232" alt="image" src="https://user-images.githubusercontent.com/44045911/229839460-827cad9f-beaf-496d-b8cd-0d6cb480700d.png">

But really, anything is better than the current one.

**Comment by mondeja** [comment]
Feel free to open a PR! 👍🏼

**Comment by mondeja** [comment]
Just released the new icon. I'm not totally convinced but as you've pointed anything is better than the previous one.

   ![image](https://user-images.githubusercontent.com/23049315/230237947-9eaa277b-6322-4997-b766-2465f3c49f9a.png)

**Comment by kidonng** [comment]
That looks much better (than mine). I think it's clear enough when putting next to other sort buttons.

The reason it may not be convincing is probably that "sort by color" is such a rare action that it has no established icon convention.

**Comment by mondeja** [comment]
> The reason it may not be convincing is probably that "sort by color" is such a rare action that it has no established icon convention.

To be clear: I'm not convinced with the design, seems to me that there is too much space on the top and bottom of the palette. The symbol in that context ("Order" control) is meaning more than enough.

If someone wants to improve that, please submit the icon to a well stablished library of symbols like [Material Design icons](https://github.com/google/material-design-icons).
