### ISSUE TITLE
CDN crashed.. images no longer loading

### ISSUE THREAD

**Issue by AvIsBeastMC** [ericcornelissen/tmp#307]
### Kind of issue 

- [ ] Feature
- [ ] Bug
- [ ] Design
- [x] Other, namely:
CDN Crash

### Description
Hi! The `cdn.simpleicons.org` images can't seem to load and the CDN has crashed... 
![image](https://github.com/simple-icons/simple-icons-website/assets/76915068/a9243ccf-0689-482c-9526-24c0b6f49c2a)
I noticed this just now as my website stopped displaying the icons when I checked...

**Comment by adamrusted** [comment]
@LitoMore

**Comment by AvIsBeastMC** [comment]
when's this going to fixed? anybody here?

**Comment by adamrusted** [comment]
> when's this going to fixed? anybody here?

I've tagged the maintainer that runs the CDN service, but we are all voluntary on this project. If you're in a major rush to get this resolved, you might be best placed using CDNJS and styling icons locally.

**Comment by AvIsBeastMC** [comment]
Ah alright, can wait then, thank you!

**Comment by LitoMore** [comment]
It's a bug related to Vercel.

Fixed in https://github.com/LitoMore/simple-icons-cdn/commit/dc1d57ab93b832be12074208f3f467c024d81b1e.
