### ISSUE TITLE
NEW UI FOR THE WEBSITE

### ISSUE THREAD

**Issue by keerthinannepamula1** [ericcornelissen/tmp#333]
### Kind of issue 

- [x] Feature
- [ ] Bug
- [x] Design
- [ ] Other, namely:

### Description
the existing UI, thou simple, clear and straight-forward, it

1. doesn't have much space between the cards which give a congested feel
2. a new shade can be added to dark mode
3. a new filter, according to alphabets or the brand's industry can be added

**Comment by keerthinannepamula1** [comment]
I'm willing to work on this issue and would like to collaborate with others!

**Comment by adamrusted** [comment]
Hey @keerthinannepamula1 - thanks for the suggestion!
We've actually had a couple of re-designs in the pipeline for _ages_ now. One of which is _much_ faster than our current site (see https://wasm.simpleicons.org/ by @mondeja - but haven't implemented it as our contributor-base is mostly JS/TS devs.

We've also toyed with using a frontend framework like React (see https://github.com/simple-icons/simple-icons-website/issues/255), but the importance of keeping things 'simple' (as in, using core JS/TS functionality) put that to bed pretty swiftly.

Before you put any time and effort into this, it'd be good to have a proper discussion around features and UI suggestions.

**Comment by adamrusted** [comment]
Also, on
> a new filter, according to alphabets or the brand's industry can be added

The website data is pulled directly from the main package. We don't have any database working behind-the-scenes, and adding industries / categories would require major re-work to our existing JSON structure.

**Comment by keerthinannepamula1** [comment]
@adamrusted thank you so much for the clarification!
