### ISSUE TITLE
Invalid SSL certificate Error code 526

### ISSUE THREAD

**Issue by hiyaabai** [ericcornelissen/tmp#337]
Invalid SSL certificate Error code 526
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_526&utm_campaign=simpleicons.org) for more information.
2024-08-06 02:35:57 UTC

**Comment by uncenter** [comment]
Thanks for reporting this! We are aware and working on a fix :)

**Comment by mondeja** [comment]
Yep, I disabled the Cloudflare proxy yesterday but forgot to re-create the simpleicons.org domain on GitHub pages settings. It should be ready in a few minutes 🤞🏼

**Comment by vickodin** [comment]
> Yep, I disabled the Cloudflare proxy yesterday but forgot to re-create the simpleicons.org domain on GitHub pages settings. It should be ready in a few minutes 🤞🏼

Still the same problem:

![image](https://github.com/user-attachments/assets/adcab930-a0a9-4f38-8d3c-846b04c58b04)

**Comment by captn3m0** [comment]
Seems resolved now.
